[package]
description = "Dynamic DNS for CloudFlare."
edition = "2021"
license = "BSD 3-Clause"
name = "cloudflare-dyndns"
repository = "https://github.com/Hellrespawn/cloudflare-dyndns"
version = "0.8.0"
default-run = "cloudflare-dyndns"

[package.metadata.cargo-machete]
ignored = ["strum"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cloudflare-dyndns"
path = "src/bin/main.rs"

[dependencies]
camino = "1.1"
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
dirs = "5.0"
fs-err = "2.11"
indexmap = { version = "2.4", features = ["serde"] }
reqwest = { version = "0.12", features = [
    "json",
    "rustls-tls",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
strum = "0.26"
strum_macros = "0.26"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
toml = { version = "0.8", features = ["preserve_order"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["user"] }
