[package]
description = "Dynamic DNS for CloudFlare."
edition = "2021"
license = "BSD 3-Clause"
name = "cloudflare-dyndns"
repository = "https://github.com/Hellrespawn/cloudflare-dyndns"
version = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4", features = ["derive"]}
color-eyre = "0.6"
dirs = "5.0"
fs-err = "2.9"
once_cell = "1.17"
reqwest = {version = "0.11", features = ["json", "rustls-tls"], default-features = false}
serde = {version = "1", features = ["derive"]}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
