[package]
description = "Dynamic DNS for CloudFlare."
edition = "2021"
license = "BSD 3-Clause"
name = "cloudflare-dyndns"
repository = "https://github.com/Hellrespawn/cloudflare-dyndns"
version = "0.5.0"
default-run = "cloudflare-dyndns"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cloudflare-dyndns"
path = "src/bin/main.rs"

[[bin]]
name = "get-public-ip"
path = "src/bin/get_public_ip.rs"

[dependencies]
async-trait = "0.1.77"
camino = "1.1"
clap = {version = "4.4", features = ["derive"]}
color-eyre = "0.6"
dirs = "5.0"
dotenvy = "0.15"
fs-err = "2.11"
once_cell = "1.19"
reqwest = {version = "0.11", features = ["json", "rustls-tls"], default-features = false}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.111"
tokio = {version = "1.35", features = ["macros", "rt-multi-thread"]}
