[package]
description = "Dynamic DNS for CloudFlare."
edition = "2024"
license = "BSD 3-Clause"
name = "cloudflare-dyndns"
repository = "https://github.com/Hellrespawn/cloudflare-dyndns"
version = "0.9.0"
default-run = "cloudflare-dyndns"

[package.metadata.cargo-machete]
ignored = ["strum"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cloudflare-dyndns"
path = "src/bin/main.rs"

[dependencies]
camino = "1.1.9"
clap = { version = "4.5.32", features = ["derive"] }
color-eyre = "0.6.3"
derive_builder = "0.20.2"
dirs = "6.0.0"
fs-err = "3.1.0"
indexmap = { version = "2.8.0", features = ["serde"] }
reqwest = { version = "0.12.14", features = [
    "json",
    "rustls-tls",
], default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.44.1", features = ["macros", "rt"] }
toml = { version = "0.8.20", features = ["preserve_order"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["user"] }
