public_ip_url = "https://example.ip"
cloudflare_token = ""

["example.com"]
records = ["example.com", "*", { type = "AAAA", name = "mail" }]

["example.nl"]
records = ["example.nl", "*", { type = "AAAA", name = "mail" }]
