public_ip_url = "https://example.ip"

[cloudflare]
token = ""

[cloudflare."example.com"]
records = ["example.com", "*", { type = "AAAA", name = "mail" }]

[bunny]
token = ""

[bunny."example.nl"]
records = ["example.nl", "*", { type = "AAAA", name = "mail" }]
